### ISSUE TITLE
Only run visible dweet

### ISSUE THREAD

**Issue by lionleaf** [dwitter-net/dwitter-frontend#102]
I believe this frontend currently runs all loaded dweets? We should implement pause/play of dweets as you scroll. (Or possibly just load/unload as mentioned in #45 )

**Comment by sigvef** [comment]
The frontend already only plays one dweet at a time. The suggestions in #45 are nice improvements, though.

**Comment by lionleaf** [comment]
You're right! I just didn't remember it, and wanted to capture it in an issue.

Closing
