### ISSUE TITLE
clicking "post as remix" on new frontend has no user feedback

### ISSUE THREAD

**Issue by aaradhyavaze** [dwitter-net/dwitter-frontend#114]
Hello, I think that some way of letting the user know that the "remix has been posted" would be nice as when I first used it I thought it was an unresponsive button and clicked multiple times - and the same dweet got published multiple times. There seems to be no way to delete them without going back to the original website either.

**Comment by lionleaf** [comment]
Thanks for the report! That certainly needs fixing :)
Deleting dweets should be possible soon, once #112 lands :)

**Comment by aaradhyavaze** [comment]
Sure, Thank you!

**Comment by lionleaf** [comment]
Pretty sure this got re-opened by mistake
