### ISSUE TITLE
delete dweet

### ISSUE THREAD

**Issue by lionleaf** [dwitter-net/dwitter-frontend#20]

**Comment by CiaccoDavide** [comment]
Deleted dweet results in blank page with no info
![2021_11_02_16_44_418_firefox_Deleted_dweet_-_Dwitter_—_Mozilla_Firefox](https://user-images.githubusercontent.com/3226096/139883965-5d7cf3cb-cf32-4598-924a-53080b036624.png)
![2021_11_02_16_44_900_firefox_Dwitter net_-_Javascript_demos_in_140_characters_](https://user-images.githubusercontent.com/3226096/139884026-f7de0c8a-aa7c-4017-b824-f132159975e9.png)

**Comment by CiaccoDavide** [comment]
I think "remix of [deleted]" could also be included in this issue:

![image](https://user-images.githubusercontent.com/3226096/139884777-f8289174-ee47-4313-ac81-e88b5f97c471.png)

![image](https://user-images.githubusercontent.com/3226096/139884888-e35eaa14-7c44-408a-9385-e0b146cc4683.png)

What should happen to the remix of a deleted dweet?

On main-dwitter `remix of [deleted]` is shown, on beta-dwitter it still shows the link to the deleted dweet
